inlineHeader = """
SPDX-License-Identifier: Apache-2.0
Copyright 2026 The OCX Authors"""

includes = [
    "ocx/**/*.bzl",
    "tests/**/*.bzl",
    "docs/**/*.bzl",
    "scripts/**/*.sh",
]
excludes = ["dist/**", "examples/**"]
