[tools]
hawkeye = "ocx.sh/hawkeye/hawkeye:latest"
actionlint = "ocx.sh/actionlint/actionlint:latest"
bazelisk = "ocx.sh/bazelbuild/bazelisk:latest"
git-cliff = "ocx.sh/git-cliff/git-cliff:latest"
task = "ocx.sh/go-task/task:latest"
lychee = "ocx.sh/lychee/lychee:latest"
shellcheck = "ocx.sh/shellcheck/shellcheck:latest"
